spring.application.name=railwiseai

# =========================
# SERVER CONFIG
# =========================
server.port=8080

# =========================
# MYSQL CONFIG
# =========================
spring.datasource.url=jdbc:mysql://localhost:3306/railwiseai
spring.datasource.username=DB_USERNAME
spring.datasource.password=DB_PASSWORD

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# JPA CONFIG
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# IMPORTANT: prevents lazy loading issues in API response
spring.jpa.open-in-view=false

# =========================
# LOGGING (optional but useful)
# =========================
logging.level.com.keyur.railwiseai=INFO
